spring:
  application:
    name: sus-agendamento
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/susdb}
    username: ${DATABASE_USERNAME:sus}
    password: ${DATABASE_PASSWORD:sus123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

# Configurações de agendamento
agendamento:
  tempo-consulta-minutos: 30
  horario-inicio: "07:00"
  horario-fim: "18:00"

# API Externa do SUS (Unidades de Saúde)
sus:
  api:
    base-url: https://apidadosabertos.saude.gov.br
    mock-enabled: true  # true = usa dados mock (API fora do ar), false = chama API real

# API Mock Server (Profissionais, Especialidades, Horários)
api:
  mock-sus-api:
    url: ${MOCK_SUS_API_URL:http://localhost:3000}

# Configuração do Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

server:
  port: 8080

logging:
  level:
    br.com.fiap.sus: DEBUG
    feign: DEBUG
